### ISSUE TITLE
Linux arm64 support

### ISSUE THREAD

**Issue by Cat7373** [anncwb/vite-plugin-imagemin#13]
There is currently no support for Linux on arm64. This is particularly important for users using a Raspberry PI or the new free pools in travis-ci.com

**Comment by anncwb** [comment]
1. Add the following to the yum source
```
[nasm]
name=The Netwide Assembler
baseurl=http://www.nasm.us/pub/nasm/stable/linux/
enabled=1
gpgcheck=0

[nasm-testing]
name=The Netwide Assembler (release candidate builds)
baseurl=http://www.nasm.us/pub/nasm/testing/linux/
enabled=0
gpgcheck=0

[nasm-snapshot]
name=The Netwide Assembler (daily snapshot builds)
baseurl=http://www.nasm.us/pub/nasm/snapshots/latest/linux/
enabled=0
gpgcheck=0
```
Create a new `Centos-Nasm.repo` under `/etc/yum.repos.d/` and copy the above content to this file

2. Execute yum install libtool automake autoconf nasm
3. Re-execute yarn install
