### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by J-env** [anncwb/vite-plugin-imagemin#14]
![image](https://user-images.githubusercontent.com/25259920/136310885-c6c53d1f-63b9-4869-bafd-cfec5796fb0c.png)

**Comment by Adaer** [comment]
同样的问题，这个有人知道如何解决吗

**Comment by Adaer** [comment]
> ![image](https://user-images.githubusercontent.com/25259920/136310885-c6c53d1f-63b9-4869-bafd-cfec5796fb0c.png)

interface SvgOption extends Options$6 {
  plugins: {
      name: string;
      reusePaths: boolean  // 在这里加了 这个属性就好了
      active?: boolean;
    }[];
}

**Comment by anncwb** [comment]
fixed 0.5.1
