### ISSUE TITLE
图片压缩为什么不放到 generateBundle 钩子里面做？

### ISSUE THREAD

**Issue by sanyuan0704** [anncwb/vite-plugin-imagemin#15]
图片压缩我看是在 closeBundle 里面完成的，为什么不放到 generateBundle 钩子里面做？直接在内存中操作完成资源压缩，然后直接写入磁盘，而不需要：
- 打包生成文件，写磁盘
- 再读取文件进行压缩
- 再次写入磁盘。

**Comment by anncwb** [comment]
generateBundle 应该是拿不到图片的

**Comment by anncwb** [comment]
fixed 0.5.1

**Comment by sanyuan0704** [comment]
不，能拿到的，第二个参数&nbsp;bundle&nbsp;对象包含所有的&nbsp;chunk&nbsp;和&nbsp;asset


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 上午9:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [anncwb/vite-plugin-imagemin] 图片压缩为什么不放到 generateBundle 钩子里面做？ (Issue #15)




 
generateBundle 应该是拿不到图片的
 
&mdash;
