### ISSUE TITLE
压缩图片未同步操作，影响后续其他文件处理

### ISSUE THREAD

**Issue by wangdson** [anncwb/vite-plugin-imagemin#16]
此插件行为会导致其他文件处理操作错乱，需要加上同步处理
我们使用其他插件去对打包文件压缩的时候，此插件代码会对其他的文件操作有影响
![image](https://user-images.githubusercontent.com/3837008/140713697-4b59c746-ada1-418f-8c9e-a8fa81cf625d.png)

**Comment by anncwb** [comment]
fixed 0.5.1
