### ISSUE TITLE
vite-plugin-legacy causes plugin to run twice on same assets

### ISSUE THREAD

**Issue by naranjamecanica** [anncwb/vite-plugin-imagemin#2]
I'm using https://github.com/vitejs/vite/tree/main/packages/plugin-legacy in my build setup to support older browsers and this causes to trigger the imagemin compression of images to run twice.

Thanks for the great plugin!

**Comment by anncwb** [comment]
Sorry, I just saw it. Let me see

**Comment by anncwb** [comment]
Can give me reproduction？I can't reproduce it

**Comment by naranjamecanica** [comment]
Sure, after the weekend I'll try to isolate it for you.

**Comment by engram-design** [comment]
This seems to be happening to me, and I believe you can guard against it in your `writeBundle()` with something like:

```js
async writeBundle(options, bundle) {
    if (options.chunkFileNames.includes('-legacy')) {
        return;
    }
```

Although that's quick-and-dirty. I imagine you can change the name of the chunk to not always be legacy, so it's likely not foolproof, but maybe a start...
