### ISSUE TITLE
getaddrinfo ENOENT raw.githubusercontent.com

### ISSUE THREAD

**Issue by HolleKitty** [anncwb/vite-plugin-imagemin#6]
Output:
‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���

**Comment by anncwb** [comment]
This is a network problem
